afk-region: 
  x: 0.0
  y: 0.0
  z: 0.0
  world: lobby
  redius: 5.0

reward:
  interval: 300 # Intervalo de tiempo para otorgar las recompensas en segundos.
  command: "key give %player_name% Koth 3"
